README.md

The README needs a link to how a project can install Precaution.

Add a GitHub App install link to README

---

README.md

Like so many other projects, it's useful to have a badge and link
to the current build status to denote the stability of the master
branch.

Add a Build Status badge to the README

---

cache.js
index.js
test/events/check_suite.rerequested.json
test/events/pull_request.opened.json

Since pull request numbers are only unique per repository there might be name conflicts when multiple requests are processed simultaneously.
Signed-off-by: Antoine Salon <asalon@vmware.com>

Use different cache subfolders per repo

---

gosec/gosec.js
test/gosec.spawn.test.js

It will be better if the input files for analyze are given by relative directory to the "directory" argument in the gosec.js file.
This is a small pr which prepares for the integration of Gosec pr.

Fix how we call gosec.js

---

bandit/bandit_report.js
cache.js
index.js

Because we depend on the GOPATH enviormental variable and it's conditions I created a /go/src folders in cache folder and because I wanted to use the functions in cache.js I had to change almost all functions in cache.js to behave differently based on which app is calling them (Gosec or Bandit).
Also I added the lines in index.js in which we call Gosec, convert the output from Gosec and merge the outputs from Bandit and Gosec into one. Also I changed a few things about how we save the files initially.
I added the cwd (current working directory) flag when spawning gosec in gosec/gosec.js. This helped me to fix bugs when calling gosec and because of this I had to change where is the file I am removing in the test/gosec.spawn.test.js file.
And in the end I changed the format of the bandit …

Integrate gosec into the app

---

.profile

I added a .profile file. In an articale from Heroku they explain what is the procfile used for:
"During startup, the container starts a bash shell that runs any code in $HOME/.profile before executing the dyno’s command."
From: https://devcenter.heroku.com/articles/dynos#startup 
First I create a bin folder (I can't upload it because it's in the .gitignore file) then I added two commands which are installing gosec.
Also I added a few lines in which I create an .env file necessary for probot. I fill this file with the enviormental variables needed by probot, those  environmental variables are on Heroku I and get them from there.

Fix the problem to use Git on Heroku

---

gosec/gosec.js

I noticed that many times we have problems with Gosec the only information we have is this:
"ERROR event: ENONET: no such file or directory <the file> in the parse output file!"
This happens because Gosec failed to run correctly but we don't know the reason.
It's much more useful to console log the logs from the Gosec call.
Here is an example of the logs which are showed:
This example is from this pull request:
https://github.com/MVrachev/Travic-CI---Tests/pull/685

Use logs for Gosec

---

gosec/gosec.js
test/fixtures/go/src/multiple_bad_files/bad_test_file.go
test/fixtures/go/src/multiple_bad_files/networking_binding_test.go
test/fixtures/go/src/multiple_bad_files/randNumTest.go
test/gosec.spawn.test.js

With this pull request I fix the dublication of issues which appears when you analyze multiple go files in the same folder.
Now I spawn Gosec the way the securego team recommended - recursive with ./...
I didn't remove the input files argument from gosec.js because that way we can figure out do we need to scan Gosec.

Fix duplicating when calling Gosec

---

gosec/gosec.js
gosec/gosec_annotations.js
gosec/gosec_report.js
index.js
test/gosec.report.test.js

Right now when there is a issue found by Gosec the path to the file will be the full path to the file in the machine where Precaution is working.
Here is an example: 
It's from this pull request: https://github.com/MVrachev/Travic-CI---Tests/pull/687/checks
Also as you can when you go to the 'Files changed' the issues are not shown there.
With this pull request I fix this with removing the unnecessary path from the issue.
Here is how it will be with this fix: 
It's from this pull request: https://github.com/MVrachev/Travic-CI---Tests/pull/695/checks
As you can see in 'Files changed' tab the issues are now shown right where the problematic code is.

Relative file paths in Gosec issues

---

test/index.test.js

After #54 I forgot to update the related test, it was passing for the wrong reasons as it checked an incorrect folder path.
Signed-off-by: Antoine Salon <asalon@vmware.com>

Fixed incorrect cleanup test

---

.travis.yml
README.md
package.json

I use jest and Codecov tool (see codecov.io) to generate a badge about our projects code coverage.
I have to call yarn test which calls jest explicitly if I want to use this tool.
Look here: [CodeCov Node js examples](https://github.com/codecov/example-node#jest).
Codecov use Travis CI to run tests and gather information about the code coverage.
I tested and this badge is dynamically updated on every commit.
You can see how it looks here:
https://github.com/securego/gosec
This badge is configured for the master branch of precaution and that's why you can't see how it looks on my fork.

Add coverage test runner and code coverage badge

---

annotations_levels.js
bandit/bandit_report.js
github_api_helper.js
gosec/gosec_report.js
index.js
merge_reports.js
test/bandit.report.test.js
test/gosec.report.test.js
test/merge.reports.test.js

I changed our summary. The messages now are making more sense.
Closes: https://github.com/vmware/precaution/issues/64
In this summary the annotations:
- with level 'failure' are errors
- with level 'warning' are warnings
- with level 'notice' are notices
Also I added a "text" field in the output object.
There I used that Bandit provides "more info" field for its issues. In the "more info" there is a link leading to the Bandit documentation of the issue.
Sadly Gosec doesn't support that now. :(
Here is an example how the new summary will look: 
It is from this example: 
https://github.com/MVrachev/Travic-CI---Tests/pull/772/checks?check_run_id=43369277

New summary

---

github_api_helper.js
index.js
test/events/check_run_rerequested.json
test/index.test.js

Closes: https://github.com/vmware/precaution/issues/80
The problem was that when the user clicked the "Re-run" button then there would be created a check run rerequest even instead of a check suite rerequest event.
I added a small code that catches that case and I created a new unit test in index.test.js and a new file check_run_rerequested.json.
The file was needed to check if we catch the check run rerequest event correctly.

Fix for rerequest button doesn't work

---

cache.js
config.js
index.js
test/index.test.js

The baseline feature is now irrelevant since we rely on GitHub to correctly filter the annotations and only display relevant ones.
This is split off from #78 to help trim it down.

Remove all baseline related code

---

package.json

Makes it easier to catch style errors quickly even when tests fail.
Signed-off-by: Antoine Salon <asalon@vmware.com>

script: run standard before test suite

---

.travis.yml

Closes: https://github.com/vmware/precaution/issues/84
I encrypted the heroku api_key and I made Travis CI to upload on every successful build.
The first section of the deploy settings is to deploy to dev-precaution dyno (heroku app) on every successful build on the master branch.
The second section is to deploy to precaution dyno (heroku app) on every successful build on a commit with tag.
That way we will deploy to precaution heroku app only on releases.

Add automatic deploy to Heroku using Travis CI

---

.travis.yml
package.json

As a service, we don't really need to support multiple node versions.
Therefore, this change limits our testing and support to just Node.js
11.

Reduce tested node versions to just 11

---

bandit/bandit_report.js
github_api_helper.js
gosec/gosec_annotations.js
gosec/gosec_report.js
linters/bandit.js
linters/gosec.js
merge_reports.js
runner.js
test/bandit.report.test.js
test/fixtures/reports/bandit_vulnerable.json
test/fixtures/reports/gosec_safe.json
test/fixtures/reports/gosec_vulnerable.json
test/gosec.report.test.js
test/gosec.spawn.test.js
test/merge.reports.test.js

This PR sits on top of #78.
Enforce a consistent schema for linter reports, move presentation logic to merge_reports and counting issue levels to linter report generation.
Report merging now handles an arbitrary number of reports.

Report generation refactoring

---

github_api_helper.js
index.js

Close: https://github.com/vmware/precaution/issues/111
One of the bugs is when you make a pull request across forks. There was an error because it searched the files from the pr in the base repository instead of the forked repository.
The second bug is when there is a pull request across forks and then when you add commit to an existing pull request we didn't catch the
pull_request.synchronize event and then Precaution will queued for ever:
NOTE: The "Re-run" button doesn't work when there is pr across forks. The problem is that GitHub API give to Precaution an empty pull request object... I think this is a bug in the GitHub API and I will contact with them.
I wanted to publish this PR as fast as I could and that is why I didn't add unit tests for across the forks PRs.
Signed-off-by: …

Fix for "across the forks" PRs problems

---

README.md
docs/manual_deployment.md

We discussed before that our README file has too many stuff in it.
It has stuff for contributers and new users and it's unessery long.
Maybe the best solution is just to have another separate page for the setup of manual deployment.

Move the setup of the manual deployment to other page

---

test/fixtures/pull_request.files.safe.json
test/index.test.js

This should make it easier to spot issues with runs returning an error for the wrong reasons (problems with the environment or crashes).
Signed-off-by: Antoine Salon <asalon@vmware.com>

Add integration test for success conclusion

---

README.md
docs/false-pos.md

Closes: https://github.com/vmware/precaution/issues/118
I was thinking that it would be a good idea to give information for the users how to handle false positives.
On another hand that means that non secure code may be introduced into the main master branch because the pull reuqest author may use this feature incorrectly.

Add false-positives documentation

---

merge_reports.js

After the refactoring of the code we forgot to return the reference links to the documentation to the problems.
The report was like that:
After merge of this pr it will be:

Return reference links in the output

---

README.md

I thought that it will be good to redirect to the documentation website instead of GitHub docs.

Redirect to docs documentation

---

docs/false-pos.md

The links in false-pos.md do not render properly in the html.  They don't show as links.  
See https://vmware.github.io/precaution/docs/false-pos.html

Update links to properly show in docs html

---

README.md

Recent PR that merged renamed the files, but the references to those docs were missed.

Broken links in README

---

eslint_plugin/eslint_plugin_annotations.js
eslint_plugin/eslint_plugin_report.js
test/eslint.plugin.report.test.js
test/fixtures/reports/eslint_safe.json
test/fixtures/reports/eslint_vulnerable.json
test/gosec.report.test.js

Part of the work outlined in the enhancement issue: https://github.com/vmware/precaution/issues/137
I added the report generation of the ESlint plugin output. 
Also, I added unit tests for the ESlint report generation and two JSON files for tests.
Additionally, I fixed two typos in test/gosec.report.test.js and test/bandit.report.test.js.
There will be at least two more pull requests for ESlint plugin security - one for the actual spawn of the plugin and the second one with a .eslintrc file for the ESlint configuration and with modification in package.json adding ESlint and the plugin itself as dependencies.

Add ESlint plugin security report files and tests

---

docs/index.md
docs/initial_setup.md

We were discussing before that it will be good if our doc main page is different.
I saw how we can do this through the creation of an index.md file in the doc/ folder.
Also, I made the links in the setup clickable.

Add different main page in doc + correct links

---

README.md
docs/index.md

Seems the there shouldn't be a "docs" path in the URL
Fixes #141

Fix the documentation URL

---

linters/bandit.js
linters/gosec.js
runner.js

Closes: #148 
When we refactored our code it looks like we forgot to give the right path to the issues found by Gosec. The result is that the issues are shown in the checks page but not into the "Files changed" page under the code problematic lines.
The problem is that Gosec gives the absolute path to the found problem but we are interested only to the relative path against the current working directory.

Fix Gosec annotation

---

bandit/bandit_annotations.js
bandit/bandit_report.js
gosec/gosec_annotations.js
test/bandit.report.test.js

The output title is little unreadable because there are no spaces.

Add spaces in the output

---

package.json
yarn.lock

There is a bug when Travis CI uses jest. This bug is fixed in the latest versions of jest and that's why we need to upgrade.

Update jest to fix a bug in Travis CI

---

gosec/gosec_annotations.js
linters/gosec.js
test/fixtures/go/src/invalid_files/sum.invalid.go
test/gosec.spawn.test.js

Related to: https://github.com/vmware/precaution/issues/142
From version 1.3 of Gosec, we get information about the possible syntax errors found from the golang parser.
That's something important to report to the user because if there are syntax errors in a file the file won't be scanned for security vulnerabilities.
Additionally, to reporting the golang syntax errors I added a unit test about this case.

Handle invalid go files with syntax errors

---

config.js
github_api_helper.js
index.js
test/index.test.js

Related to: https://github.com/vmware/precaution/issues/134
In order to download all of the diff files from a pull request, we have to access the data from GitHub page by page.
Also, there is an option to customize how many results do you want per page.
I added a unit test handling the paging but I  had to change the other unit tests a little bit in order to achieve that.

Download more than 30 files

---

yarn.lock

There is an error in Travis CI when deploying to Heroku.
The reason for that is that there is a difference between yarn.lock and package.json.
Here is want Heroku are saying about this problem:
"If the dependencies in package.json change, but a new yarn.lock file is not generated by the Yarn executable we fail the build to prevent subtle bugs and security issues that could affect your application at runtime."
https://help.heroku.com/TXYS53YJ/why-is-my-node-js-build-failing-because-of-an-outdated-yarn-lockfile

Add yarn.lock changes

---

index.js

Fixes: https://github.com/vmware/precaution/issues/170
Instead of awaiting the finish of the runLinterFromPRData function it's required by probot to execute it asynchronously so probot can send a response for the inial request.

Fix for request timeout from Heroku

---

config.js
linters/index.js
linters/tslint.js
test/fixtures/typescript/safe.js
test/fixtures/typescript/vulnerable.js
test/tslint.spawn.test.js

I added a TSLint spawn functionality + unit tests for that.
Because the TSLint rules for TypeScript are 100% compatible with JavaScript (those are the words from the maintainer of the TSLint security rules project) I tested only on vulnerable JavaScript file.
Sadly, TSLint doesn't report you when you try to scan an invalid file with syntax errors. That's why I haven't added more sophisticated functionality in parseResults function in linters/tslint.js 

TSLint spawn functionality

---

linters/bandit.js
linters/gosec.js
test/bandit.spawn.test.js
test/gosec.spawn.test.js

It's a lot clearer what is bandit_output.json instead of just bandit.json.
Also, maybe we would have to use configuration files for the linters in future and many times those files are called "linterName.json".
We already stumped upon that situation with TSLint.

Linters output files rename

---

.mergify.yml

The Mergify GitHub App is already installed to the Precaution
repo.  This commit enables the app by setting necessary configuration
via the YAML file.
Note that this config sets the following conditions
- The number of approved code reviews must be 1 or greater
- The Travis CI must pass
- Enabled on branch master only
- Don't merge PRs with work-in-progress label
- And finally, only merge with label ready-to-merge
https://doc.mergify.io

Enable Mergify for automatic merges

---

cache.js
index.js

Connected with: https://github.com/vmware/precaution/issues/160
Refactor code for new linters In our code on many places is like there will be no other linters in the future besides Bandit and Gosec.
That is something worth to change.

Refactor for new linters

---

test/fixtures/annotations/tslint_mix_annotations.json
test/fixtures/pull_request.files.mix.json
test/index.test.js
test/merge.reports.test.js

Connected with issue: https://github.com/vmware/precaution/issues/160
When we check if we download the right files it's a good idea to add js
and ts files there too. Same applies in the merge report unit tests.

Add js and ts files into unit tests

---

bandit/bandit_report.js
config.js
merge_reports.js

It's better to have that "reference links" title separated from the
Bandit "more info" implementation. That way when we have reference links
from the other linters it will be possible and easier to add them.

Move "reference links" title to config.js

---

package.json

The contributor list was outdated. This commit also removes the
author since no single person has "authored" the code. Ideally
we could set the author to a mailing list, but we currently don't
have one.
Partially-fixes #166

Update the list of contributors

---

README.md
docs/_config.yml
docs/index.md

Enable relative links so that when running a local Jekyll instance or
browsing the Markdown documentation files from the GitHub file browser
documentation links don't take us away from the GitHub browser.
The Jekyll jekyll-relative-links plugin is enabled by default on GitHub
pages:
https://help.github.com/en/articles/configuring-jekyll-plugins#default-plugins

Make documentation links relative

---

test/annotation.levels.test.js
test/bandit.report.test.js
test/check.run.conclusion.test.js
test/gosec.report.test.js
test/merge.reports.test.js
test/tslint.report.test.js

The idea of the unit tests is to be independent of the order they will
be executed. That's why it makes sense to make them asynchronous and
thus make the execution of the tests faster.

Make all tests asynchronous

---

docs/false_positivies.md

Fix the syntax highlighting for the JavaScript code block and syntax
highlighting to the Python code block.

Syntax highlighting for all examples in false positives document

---

CODE_OF_CONDUCT.md

VMware has a proper mailing list to report code-of-conduct abuses
at oss-coc@vmware.com.

Update the COC with official mailing list

---

.gitignore
docs/Gemfile
docs/_config.yml
docs/index.md
docs/local_docs_build.md

Some changes to make generating documentation a bit nicer:
1) Add Gemfile to ease generating docs locally
2) Document the process for generating the documentation

Add machinery and docs for local generation of documentation

---

docs/manual_deployment.md

Steps 3 and 4 from the "Setting up a manual deployment"
doc should be done before step 2.
Using the current order doesn't work because the GOPATH is needed
in order to install Gosec.
Another problem is that we are downloading Gosec with "go get".
That means that we are downloading the latest commit from the
master branch which can be unstable.
It's a lot better to download a specific version.

Reorder steps and tweaks in manual deployment

---

docs/manual_deployment.md

We miss a really important step in the manual deployment doc and
it is about installing node and JavaScript/TypeScript dependencies
as a whole.
Without this step, Precaution won't run.

Add JS/TS dependencies in manual deployment docs

---

docs/manual_deployment.md

Pip is required before installing Bandit through
requirements.txt and we should document that.

Add pip install step in manual deployment doc

---

index.js

We don't need to respond to CheckSuiteEvent when the action is requested.
We are already listening to the events:
- pull_request: opened/reopened/synchronize
- check_run/check_suite rerequest
which are enough for us to do our work.
Our event handling covers the following scenarios:
- pull request from forked repo to the original repo
- pull request from repo to itself
- when clicked re-run-all-checks/re-run buttons on the UI on already
opened pull request
Fixes: #169 

Remove spurious handling of CheckSuiteEvent's requested action

---

config.js
package.json
test/external.dependencies.test.js
tslint/tslint_report.js

Add support for TSLint reference links
Because TSLint doesn't provide us with reference links and doesn't have
an API for such metadata as explained by the developer of
tslint-config-security: webschik/tslint-config-security#17
All rules are documented as part of the README for
tslint-config-security on GitHub, therefore we can use this
documentation to provide reference links.
Another thing we should check is if every rule has a documentation on
the project webpage and do we point to that documentation.

 Add support for TSLint reference links

---

github_api_helper.js
index.js
test/annotation.levels.test.js
test/bandit.report.test.js
test/check.run.conclusion.test.js
test/gosec.report.test.js
test/index.test.js
test/merge.reports.test.js
test/tslint.report.test.js

Nodejs is single threaded but uses an event loop
for Asynchronous calls.
It has an async/await mechanism which should be used when we have
external service or when we need to wait for a data
(and we don't have immediate access to it).
Practically that translates to the simple idea that if we are calling
one function that is async or if it returns a Promise
then we need to await the result of that function and thus use our
own async function.

Remove redundant async keyword

---

README.md

Our documentation grows and having all links in our README.md
will require more and more space.
Also, when we add more docs we will have to update docs/index.md
and README.md at the same time.

Remove additional documentation from README

---

docs/architecture.md

We are opting to ignore tool specific configuration files which may exist in
the repository and only use configuration which has been set in precaution.json
This strategy allows us to expose relevant functionality common to all
supported linters in a consistent fashion. Furthermore by not exposing tool
specific configuration via Precaution we don't have to worry about migration
paths should we choose to change the underlying tools in future.
Closes: #81

Document our decision to ignore tool specific configuration files

---

linters/tslint.js

Trivial fix to add the dot so that the filter only matches files
with a ts extension and not any file ending in ts.
Fixes issue #224

The tslint plugin should filter on *.ts not *ts

---

docs/manual_deployment.md

One student wants to contribute to Precaution and after
reading through our doc for manual deployment he gave some
suggestions.
It will be useful if we clarify how you can clone Precaution
and that you should run pip from the root directory of the project.
Because if you have never used Python it's possible
to make a mistake.

Setting up for manual_deployment doc tweaks

---

config.js

Some of file extensions were listed in the fileExtensions array with a
preceding '.' and others were not. We must be consistent in using the '.'
prefix to all file extensions in the array, otherwise we may have unexpected
behaviours such as the filterData() function in github_api_helper.js
matching all filenames that end with 'js' or 'ts'.

Fix filename extensions in config.fileExtensions to have preceding '.'

---

config.js
filter.js
github_api_helper.js
index.js
package-lock.json
package.json
test/config.options.test.js
test/fixtures/config_files/sample_config.yaml
test/fixtures/pull_request.files.mix.json
test/index.test.js

Our users need a way to configure Precaution for their needs.
The first important option to enable will be the "exclude" option.
That way the users can exclude their tests folders and files.
We decided to give globs as a way for the users to be more flexible
when they are creating exclude rules.
Because YAML allows you to use comments and it's more human readable
than JSON we decided to use .precaution.yaml as a config file.
Closes: https://github.com/vmware/precaution/issues/179

Add configuration file support and exclude option

---

README.md

We are using the badge for travis-ci.com instead
of travis-ci.org which we are using right now.

Change the build badge link of Travis CI

---

docs/index.md

We have forgotten to change the badge of Travis CI from
https://travis-ci.com to https://travis-ci.org in the
documentation main page.

Change the badge of Travis CI in the docs

---

docs/index.md

We forgot to add a reference to the newly added documentation for
"Setting up Precaution as branch protection rule"

Add reference to the doc for branch protection rule

---

docs/manual_deployment.md

In our doc "Setting up a manual deployment" we didn't emphasize
how important it is to redirect the GitHub webhooks to your local
machine.
Without this step you can't see how Precaution actually works!

Make "Redirect Github webhooks" step mandatory

---

docs/index.md
docs/issues_catched.md

When a user sees our repository it's important to
give good argumentation about why he should use our app.
Having documentation which roughly groups what issues
are found by Precaution is a good and valid argument
for that
Closes: https://github.com/vmware/precaution/issues/178

Add doc for what issues Precaution catch

---

yarn.lock

We need to upgrade handlebars to a version which isn't vulnerable to
CVE-2019-19919 and thus need to upgrade all of the packages which pull in
that version of handlebars.

yarn.lock: upgrade dependencies
